spring:
  profiles:
    active: ${server.profile:local}
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail_id}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#logging:
#  pattern:
#    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
#  level:
#    root: info
#    ai.serverapi: info

server:
  port: 8000

api-prefix: /api
docs: /docs/docs.html

kakao:
  client_id: ${kakao_id}
  redirect_url: ${kakao_url}

cloud:
  s3:
    bucket: cherryandplum
    access-id: ${s3_id}
    secret-key: ${s3_secret}
    url: https://cherryandplum.s3.ap-northeast-2.amazonaws.com
#    size: 10485760  # 10MB

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWp1bm8tc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWp1bm8tYXBwbGluZwo=