version: "3"
services:
  master:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: master
    environment:
      MYSQL_DATABASE: 'serverapi'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./data:/var/lib/mysql-files
    networks:
      net:
        ipv4_address: 192.168.14.3


networks:
  net:
    external:
      name: normal


# docker network create normal --subnet=192.168.14.0/24
# CHANGE MASTER TO MASTER_HOST='192.168.14.3', MASTER_USER='root', MASTER_PASSWORD='password', MASTER_LOG_FILE='mysql-bin.000001', MASTER_LOG_POS=0, GET_MASTER_PUBLIC_KEY=1;